# Generated by Django 4.1.4 on 2022-12-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PythonQuesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True, verbose_name='Вопрос')),
                ('op1', models.CharField(max_length=200, null=True, verbose_name='Вариснт 1')),
                ('op2', models.CharField(max_length=200, null=True, verbose_name='Вариснт 2')),
                ('op3', models.CharField(max_length=200, null=True, verbose_name='Вариснт 3')),
                ('ans', models.CharField(max_length=200, null=True, verbose_name='Ответ')),
            ],
        ),
    ]
